### ISSUE TITLE
Issue starting nginx_docker on Ubuntu 18.04 server

### ISSUE THREAD

**Issue by ghost** [JINWOO-J/nginx_docker#13]
we found some issue when we try to start nginx-docker with  $ make (see the error log below)
We are using Ubuntu 18.04 server.

 ~/nginx_docker $ make
sed -i '' "s/looploy\/nginx.*/looploy\/nginx:1.17.1/g" docker-compose_grpc.yml
sed: can't read s/looploy\/nginx.*/looploy\/nginx:1.17.1/g: No such file or directory
Makefile:29: recipe for target 'build' failed
make: *** [build] Error 2

**Comment by JINWOO-J** [comment]
The problem you reported has been solved.  Can you let me know after you check? It was a sed option problem on ubuntu.
